{
    'name': 'GMS',
    'application': True,
    'data': [
        'security/groups.xml',
        'security/rules.xml',
        'security/hr_attendance_security.xml',
        'security/ir.model.access.csv',

        'views/validity_period_view.xml',
        'views/hr_attendance_raw_data_views.xml',
        'views/inherit_attendances_views.xml',
        'views/import_history_views.xml',
        'views/inherit_time_off_approval_views.xml',
        'views/gms_calendar.xml',
        'views/inherit_department_views.xml',
        'views/inherit_res_user.xml',
        'views/inherit_employee_view.xml',
        'views/inherit_time_off.xml',

        'report/hr_attendance_report.xml',
        'report/hr_attendance_wfh_views.xml',
        'report/report_work_location_summary_xlsx.xml',

        'wizard/work_from_home_views.xml',
        'wizard/gms_work_location_report_wizard_view.xml',

        'data/attendance_approve.xml',
        'data/mail_template_data.xml',
        'data/config_data.xml',
        'data/mail_activity_types.xml',
        'data/day_of_week.xml',
        'data/menu.xml',
    ],
    'depends': [
        'base',
        'hr',
        'hr_attendance',
        'hr_holidays',
        'web',
        'mail',
        'calendar',
        'resource',
        'report_xlsx',
    ],
    'assets': {
        'web.assets_backend': [
            '/gms/static/src/js/transform_button.js',
            '/gms/static/src/xml/transform_button.xml',
            '/gms/static/src/js/work_from_home_button.js',
            '/gms/static/src/xml/work_from_home_button.xml',
            # '/gms/static/src/xml/pivot_filter.xml',
            # '/gms/static/src/js/pivot_filter.js',
            '/gms/static/src/js/date_range_gm.js',
            '/gms/static/src/js/control_panel.js',
            '/gms/static/src/js/daterangepicker_min.js',
            '/gms/static/src/js/widget_time_off.js',
            '/gms/static/src/xml/redirect_email.xml',
            '/gms/static/src/xml/template.xml',
            '/gms/static/src/js/department.js',
            '/gms/static/src/css/*.scss',
            # '/gms/static/src/js/get_session.js',
            # '/gms/static/src/js/chat_bot.js',
        ]
    },
}
